import type { Metadata } from "next";

import "./globals.css";
import { ClusterProvider } from '@/cluster/cluster-data-access'
import { SolanaProvider } from '@/providers/SolanaProvider'
import { Space_Mono } from 'next/font/google'

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-space-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceMono.variable}`}>
      <body

      >
        <body className="font-sans bg-[#0b0b1c] text-white"></body>
        <ClusterProvider>
          <SolanaProvider>
            {children}
          </SolanaProvider>
        </ClusterProvider>
      </body>
    </html>
  );
}
